/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan.transaksi;
import Koneksi.Koneksi;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;import tampilan.dashboard.dashboard;

/**
 *
 * @author raisa
 */
public class FormKerusakan extends javax.swing.JFrame {
    DefaultTableModel model;
    /**
     * Creates new form FormKerusakan
     */
    public FormKerusakan() {
        initComponents();
        jDateKB.setDateFormatString("dd/MM/yyyy");
        aturTabel();      
        otomatisID();     
        tampilPetugas();  
        tampilBarang();
    }
    private void aturTabel() {
        model = new DefaultTableModel();
        tableTransaksi.setModel(model);
        model.addColumn("ID Barang");
        model.addColumn("Nama Barang");
        model.addColumn("Qty");
        model.addColumn("Keterangan");
    }

    private void otomatisID() {
        try {
        Connection conn = Koneksi.getKoneksi();
        // Gunakan MAX untuk mencari angka paling besar
        String sql = "SELECT MAX(id_kerusakan) FROM kerusakan WHERE id_kerusakan LIKE 'KSK%'";
        Statement st = conn.createStatement();
        ResultSet rs = st.executeQuery(sql);
        
        if (rs.next() && rs.getString(1) != null) {
            String idTerakhir = rs.getString(1); // Contoh "KSK0002"
            
            // Potong teks "KSK" dan ambil angkanya (Index ke-3)
            int nomor = Integer.parseInt(idTerakhir.substring(3)); 
            nomor++; // Tambah 1
            
            // Format ulang dengan padding 0 di depan agar konsisten 4 digit angka
            String kode = String.format("KSK%04d", nomor);
            txtId.setText(kode);
        } else {
            // Jika tabel masih kosong
            txtId.setText("KSK0001"); 
        }
        txtId.setEditable(false);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal membuat ID Otomatis: " + e.getMessage());
        txtId.setText("KSK0001");
        txtId.setEditable(false);
    }
    }

    
    private void tampilPetugas() {
    try {
        Connection conn = Koneksi.getKoneksi();
        String sql = "SELECT username FROM user"; 
        Statement st = conn.createStatement();
        ResultSet rs = st.executeQuery(sql);
        
        cbPetugas.removeAllItems();
        cbPetugas.addItem("- Pilih Petugas -");
        while (rs.next()) {
            cbPetugas.addItem(rs.getString("username"));
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal memuat petugas: " + e.getMessage());
    }
}

    
    private void tampilBarang() {
    try {
        Connection conn = Koneksi.getKoneksi();
        String sql = "SELECT nama_barang FROM barang"; 
        Statement st = conn.createStatement();
        ResultSet rs = st.executeQuery(sql);
        
        cbBarang.removeAllItems();
        cbBarang.addItem("- Pilih Barang -");
        while (rs.next()) {
            cbBarang.addItem(rs.getString("nama_barang"));
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal memuat data barang: " + e.getMessage());
    }
}
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        cbBarang = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        spJumlah = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtKeterangan = new javax.swing.JTextArea();
        btnTambah = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbPetugas = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtIDP = new javax.swing.JTextField();
        jDateKB = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableTransaksi = new javax.swing.JTable();
        btnHome = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        jLabel6.setText("jLabel6");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 204, 204));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Input Data Kerusakan"));

        jLabel7.setText("Barang: ");

        cbBarang.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N

        jLabel8.setText("Jumlah Rusak (Qty): ");

        spJumlah.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jLabel9.setText("Keterangan Kerusakan: ");

        txtKeterangan.setColumns(20);
        txtKeterangan.setRows(5);
        jScrollPane1.setViewportView(txtKeterangan);

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTambah))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTambah))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 140, 510, 230));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Kerusakan"));

        jLabel2.setText("ID Kerusakan: ");

        txtId.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        txtId.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel3.setText("Tanggal: ");

        jLabel4.setText("Petugas: ");

        cbPetugas.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        cbPetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPetugasActionPerformed(evt);
            }
        });

        jLabel5.setText("ID Petugas:");

        txtIDP.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        txtIDP.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtIDP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDPActionPerformed(evt);
            }
        });

        jDateKB.setDateFormatString("dd-MM-yyyy");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                        .addComponent(txtId)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jDateKB, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                        .addComponent(txtIDP))
                    .addComponent(cbPetugas, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbPetugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateKB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, 230));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FORM KERUSAKAN BARANG");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 1200, 47));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel10.setText("DAFTAR KERUSAKAN BARANG");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, 510, 29));

        tableTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tableTransaksi);

        jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 440, 523, 110));

        btnHome.setBackground(new java.awt.Color(204, 255, 255));
        btnHome.setText("HOME");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        jPanel4.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 70, -1, -1));

        btnBatal.setBackground(new java.awt.Color(153, 153, 153));
        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });
        jPanel4.add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 570, 78, -1));

        btnSimpan.setBackground(new java.awt.Color(0, 255, 0));
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        jPanel4.add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 570, -1, -1));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 1200, 640));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Animasi Min 18 Jakarta 8.png"))); // NOI18N
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -170, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 2050, 1460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
    int jumlahBaris = tableTransaksi.getRowCount();
    
    // 1. Validasi jika tabel item kerusakan masih kosong
    if (jumlahBaris == 0) {
        JOptionPane.showMessageDialog(this, "Tabel transaksi item masih kosong!");
        return;
    }
    
    // 2. Validasi jika tanggal belum dipilih pada JDateChooser (jDateKB)
    if (jDateKB.getDate() == null) {
        JOptionPane.showMessageDialog(this, "Silakan pilih tanggal transaksi terlebih dahulu!");
        return;
    }
    
    try {
        Connection conn = Koneksi.getKoneksi();
        
        // 3. Format tanggal dari jDateKB ke format database (yyyy-MM-dd)
        java.util.Date date = jDateKB.getDate();
        java.sql.Date sqlDate = new java.sql.Date(date.getTime());
        
        // 4. Query INSERT & UPDATE
        String sqlInsert = "INSERT INTO kerusakan (id_kerusakan, tanggal, id_barang, jumlah_rusak, keterangan, id_user) VALUES (?, ?, ?, ?, ?, ?)";
        PreparedStatement pstInsert = conn.prepareStatement(sqlInsert);
        
        String sqlUpdateStok = "UPDATE barang SET stok = stok - ? WHERE id_barang = ?";
        PreparedStatement pstUpdate = conn.prepareStatement(sqlUpdateStok);
        
        // 5. PERBAIKAN: Ambil angka dasar dari TextBox ID (Misal "KSK0002" -> Angka 2)
        int angkaDasar = Integer.parseInt(txtId.getText().substring(3));
        
        // 6. Loop memproses semua baris data dari JTable transaksi kerusakan
        for (int i = 0; i < jumlahBaris; i++) {
            String idBarang   = tableTransaksi.getValueAt(i, 0).toString();
            int qty           = Integer.parseInt(tableTransaksi.getValueAt(i, 2).toString());
            String keterangan = tableTransaksi.getValueAt(i, 3).toString();
            
            // PERBAIKAN: Generate ID Baru otomatis untuk setiap baris di tabel (KSK0002, KSK0003, dst)
            String idKerusakanUnik = String.format("KSK%04d", angkaDasar + i);
            
            // Masukkan parameter untuk Simpan ke tabel kerusakan
            pstInsert.setString(1, idKerusakanUnik); // Gunakan ID Unik, jangan txtId.getText()
            pstInsert.setDate(2, sqlDate);
            pstInsert.setString(3, idBarang); 
            pstInsert.setInt(4, qty); 
            pstInsert.setString(5, keterangan); 
            pstInsert.setString(6, txtIDP.getText());
            pstInsert.addBatch(); 
            
            // Masukkan parameter untuk Potong Stok di tabel barang
            pstUpdate.setInt(1, qty);         
            pstUpdate.setString(2, idBarang); 
            pstUpdate.addBatch();             
        }
        
        // 7. Eksekusi semua perintah batch sekaligus ke Database
        pstInsert.executeBatch();
        pstUpdate.executeBatch();
        
        pstInsert.close();
        pstUpdate.close();
        
        JOptionPane.showMessageDialog(this, "Sukses! Data Kerusakan Berhasil Disimpan dan Stok Barang Otomatis Dikurangi.");
        
        // 8. Reset inputan form ke kondisi semula setelah berhasil
        model.setRowCount(0);
        cbPetugas.setSelectedIndex(0);
        cbBarang.setSelectedIndex(0);
        spJumlah.setValue(1);
        txtKeterangan.setText("");
        txtIDP.setText("");
        jDateKB.setDate(null); 
        otomatisID(); // Generate ID baru
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal menyimpan transaksi atau mengurangi stok: " + e.getMessage());
    }  // TODO add your handling code here:
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
    if (cbBarang.getSelectedIndex() == 0 || txtIDP.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Silakan lengkapi data petugas dan barang terlebih dahulu!");
            return;
        }
        
        try {
            Connection conn = Koneksi.getKoneksi();
            String sql = "SELECT id_barang FROM barang WHERE nama_barang = ?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, cbBarang.getSelectedItem().toString());
            ResultSet rs = pst.executeQuery();
            
            if (rs.next()) {
                String idBarang = rs.getString("id_barang");
                String namaBarang = cbBarang.getSelectedItem().toString();
                int qty = (int) spJumlah.getValue();
                String keterangan = txtKeterangan.getText();
                
             
                model.addRow(new Object[]{idBarang, namaBarang, qty, keterangan});
                
               
                cbBarang.setSelectedIndex(0);
                spJumlah.setValue(1);
                txtKeterangan.setText("");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal menambahkan item: " + e.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
    model.setRowCount(0);
        cbPetugas.setSelectedIndex(0);
        cbBarang.setSelectedIndex(0);
        spJumlah.setValue(1);
        txtKeterangan.setText("");
        otomatisID();    // TODO add your handling code here:
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
     dashboard db = new dashboard();

    db.setVisible(true);

    this.dispose();      // TODO add your handling code here:
    }//GEN-LAST:event_btnHomeActionPerformed

    private void txtIDPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDPActionPerformed

    private void cbPetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPetugasActionPerformed
    if (cbPetugas.getSelectedIndex() > 0) {
        try {
            Connection conn = Koneksi.getKoneksi();
            String sql = "SELECT id_user FROM user WHERE username = ?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, cbPetugas.getSelectedItem().toString());
            ResultSet rs = pst.executeQuery();
            
            if (rs.next()) {
                txtIDP.setText(rs.getString("id_user"));
            }
            txtIDP.setEditable(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat ID Petugas: " + e.getMessage());
        }
    } else {
        txtIDP.setText("");
    }    // TODO add your handling code here:
    }//GEN-LAST:event_cbPetugasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormKerusakan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormKerusakan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormKerusakan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormKerusakan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormKerusakan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JComboBox<String> cbBarang;
    private javax.swing.JComboBox<String> cbPetugas;
    private com.toedter.calendar.JDateChooser jDateKB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JSpinner spJumlah;
    private javax.swing.JTable tableTransaksi;
    private javax.swing.JTextField txtIDP;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextArea txtKeterangan;
    // End of variables declaration//GEN-END:variables
}
