/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan.master;
import Koneksi.Koneksi;
import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author raisa
 */
public class FormUser extends javax.swing.JFrame {
    private Connection conn = Koneksi.getKoneksi(); 
    private DefaultTableModel tabmode;

    public FormUser() {
        initComponents();
        setTitle("Form Data User");
        kosong();
        datatable();
        autoId();
        
        
        cblevel.removeAllItems();
        cblevel.addItem("Admin");
        cblevel.addItem("User");
    }

    protected void kosong() {
        txtuser.setText("");
        txtpass.setText("");
        cblevel.setSelectedIndex(0);
        txtcari.setText("");
    }
    /**
     * Creates new form FormUser
     */
    protected void datatable() {
    Object[] Baris = {"ID User", "Username", "Password", "Level"};
    tabmode = new DefaultTableModel(null, Baris);
    String cari = txtcari.getText();
    
    try {
        // Mencari user berdasarkan username
        String sql = "SELECT * FROM user WHERE username LIKE '%" + cari + "%' ORDER BY id_user ASC";
        Statement stat = conn.createStatement();
        ResultSet hasil = stat.executeQuery(sql);
        while (hasil.next()) {
            tabmode.addRow(new Object[]{
                hasil.getString("id_user"),
                hasil.getString("username"),
                "********", // Password tidak ditampilkan demi keamanan
                hasil.getString("level")
            });
        }
        tbluser.setModel(tabmode);
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Data gagal dipanggil: " + e);
    }
}

private void autoId() {
    try {
        String sql = "SELECT MAX(id_user) FROM user";
        ResultSet rs = conn.createStatement().executeQuery(sql);
        if (rs.next() && rs.getString(1) != null) {
            String id = rs.getString(1);
            int angka = Integer.parseInt(id.substring(1)); 
            angka++;
            txtid.setText(String.format("U%03d", angka));
        } else {
            txtid.setText("U001");
        }
    } catch (Exception e) {
        txtid.setText("U001");
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbluser = new javax.swing.JTable();
        bcari = new javax.swing.JButton();
        txtcari = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        bsimpan = new javax.swing.JButton();
        bedit = new javax.swing.JButton();
        bhapus = new javax.swing.JButton();
        bbatal = new javax.swing.JButton();
        bkeluar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtuser = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtpass = new javax.swing.JPasswordField();
        cblevel = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbluser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbluser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbluserMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbluser);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 480, 544, 110));

        bcari.setBackground(new java.awt.Color(153, 204, 255));
        bcari.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        bcari.setText("CARI");
        bcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcariActionPerformed(evt);
            }
        });
        bcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bcariKeyPressed(evt);
            }
        });
        jPanel2.add(bcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, -1, -1));

        txtcari.setBackground(new java.awt.Color(0, 204, 204));
        txtcari.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtcari.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel2.add(txtcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, 142, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel6.setText("Data User");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 115, 31));

        bsimpan.setBackground(new java.awt.Color(0, 255, 0));
        bsimpan.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        bsimpan.setText("SIMPAN");
        bsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsimpanActionPerformed(evt);
            }
        });
        jPanel2.add(bsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, -1, -1));

        bedit.setBackground(new java.awt.Color(0, 204, 255));
        bedit.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        bedit.setText("EDIT");
        bedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beditActionPerformed(evt);
            }
        });
        jPanel2.add(bedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, -1, -1));

        bhapus.setBackground(new java.awt.Color(255, 51, 51));
        bhapus.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        bhapus.setText("HAPUS");
        bhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhapusActionPerformed(evt);
            }
        });
        jPanel2.add(bhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 290, -1, -1));

        bbatal.setBackground(new java.awt.Color(153, 153, 153));
        bbatal.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        bbatal.setText("BATAL");
        bbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbatalActionPerformed(evt);
            }
        });
        jPanel2.add(bbatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 290, -1, -1));

        bkeluar.setBackground(new java.awt.Color(255, 102, 0));
        bkeluar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        bkeluar.setText("KELUAR");
        bkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkeluarActionPerformed(evt);
            }
        });
        jPanel2.add(bkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 80, -1, -1));

        jLabel2.setText("ID USER");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 162, 31));

        txtid.setBackground(new java.awt.Color(0, 204, 204));
        txtid.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtid.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel2.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 181, 31));

        txtuser.setBackground(new java.awt.Color(0, 204, 204));
        txtuser.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtuser.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel2.add(txtuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 181, 30));

        jLabel3.setText("USERNAME");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 162, 30));

        txtpass.setEditable(false);
        txtpass.setBackground(new java.awt.Color(0, 204, 204));
        txtpass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel2.add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 140, 181, 29));

        cblevel.setBackground(new java.awt.Color(0, 204, 204));
        cblevel.setEditable(true);
        cblevel.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        cblevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Admin", "User" }));
        cblevel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel2.add(cblevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 210, 181, -1));

        jLabel5.setText("LEVEL");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, 162, 31));

        jLabel4.setText("PASSWORD");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, 162, 31));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 35)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FORM DATA USER");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 940, 48));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 290, 950, 640));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Animasi Min 18 Jakarta 5.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -190, 2050, 1370));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 2050, 1180));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhapusActionPerformed
    String sql = "UPDATE user SET username=?, password=?, level=? WHERE id_user=?";
    try {
        PreparedStatement stat = conn.prepareStatement(sql);
        stat.setString(1, txtuser.getText());
        stat.setString(2, txtpass.getText());
        stat.setString(3, cblevel.getSelectedItem().toString());
        stat.setString(4, txtid.getText());

        stat.executeUpdate();
        JOptionPane.showMessageDialog(null, "Data User Diperbarui");
        kosong();
        datatable();
        autoId();
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Gagal Edit: " + e);
    }    // TODO add your handling code here:
    }//GEN-LAST:event_bhapusActionPerformed

    private void bsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsimpanActionPerformed
    String sql = "INSERT INTO user VALUES (?,?,?,?)";
    try {
        PreparedStatement stat = conn.prepareStatement(sql);
        stat.setString(1, txtid.getText());
        stat.setString(2, txtuser.getText());
        stat.setString(3, txtpass.getText()); 
        stat.setString(4, cblevel.getSelectedItem().toString());

        stat.executeUpdate();
        JOptionPane.showMessageDialog(null, "User Berhasil Ditambahkan");
        kosong();
        datatable();
        autoId();
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Gagal Simpan: " + e);
    } // TODO add your handling code here:
    }//GEN-LAST:event_bsimpanActionPerformed

    private void beditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beditActionPerformed
    String sql = "UPDATE user SET username=?, password=?, level=? WHERE id_user=?";
    try {
        PreparedStatement stat = conn.prepareStatement(sql);
        stat.setString(1, txtuser.getText());
        stat.setString(2, txtpass.getText());
        stat.setString(3, cblevel.getSelectedItem().toString());
        stat.setString(4, txtid.getText());

        stat.executeUpdate();
        JOptionPane.showMessageDialog(null, "Data User Diperbarui");
        kosong();
        datatable();
        autoId();
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Gagal Edit: " + e);
    }    // TODO add your handling code here:
    }//GEN-LAST:event_beditActionPerformed

    private void tbluserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbluserMouseClicked
    int bar = tbluser.getSelectedRow();
    txtid.setText(tabmode.getValueAt(bar, 0).toString());
    txtuser.setText(tabmode.getValueAt(bar, 1).toString());
    }//GEN-LAST:event_tbluserMouseClicked

    private void bbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbatalActionPerformed
    kosong();
    datatable();     // TODO add your handling code here:
    }//GEN-LAST:event_bbatalActionPerformed

    private void bcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcariActionPerformed
    datatable();     // TODO add your handling code here:
    }//GEN-LAST:event_bcariActionPerformed

    private void bcariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bcariKeyPressed
     if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            datatable();
        }     // TODO add your handling code here:
    }//GEN-LAST:event_bcariKeyPressed

    private void bkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkeluarActionPerformed
     // Panggil form menu utama
    this.dispose();    // TODO add your handling code here:
    }//GEN-LAST:event_bkeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bbatal;
    private javax.swing.JButton bcari;
    private javax.swing.JButton bedit;
    private javax.swing.JButton bhapus;
    private javax.swing.JButton bkeluar;
    private javax.swing.JButton bsimpan;
    private javax.swing.JComboBox<String> cblevel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbluser;
    private javax.swing.JTextField txtcari;
    private javax.swing.JTextField txtid;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
