/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tampilan.master;
import Koneksi.Koneksi;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import tampilan.dashboard.dashboard;
/**
 *
 * @author andre_f1brqrv
 */
public class FormBarang extends javax.swing.JFrame {

    /** Creates new form menubarang */
    public FormBarang() {
        initComponents();
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        setTitle("ini form barang");
        tampilData();
        loadKategori();
        loadLokasi();
        autoId();
        
        
    cbKondisi.removeAllItems();
    cbKondisi.addItem("Baik");
    cbKondisi.addItem("Rusak");
    }

     private void tampilData() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID");
    model.addColumn("Nama");
    model.addColumn("Kategori");
    model.addColumn("Stok");
    model.addColumn("Kondisi");
    model.addColumn("Lokasi");

    try {
        String sql = "SELECT * FROM barang";
        ResultSet rs = Koneksi.getKoneksi().createStatement().executeQuery(sql);

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString("id_barang"),
                rs.getString("nama_barang"),
                rs.getString("id_kategori"),
                rs.getString("stok"),
                rs.getString("kondisi"),
                rs.getString("lokasi")
            });
        }

        tableBarang.setModel(model);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }
}

    private void loadKategori() {
    try {
        cbKategori.removeAllItems();

        String sql = "SELECT * FROM kategori";
        ResultSet rs = Koneksi.getKoneksi().createStatement().executeQuery(sql);

        while (rs.next()) {
            cbKategori.addItem(rs.getString("nama_kategori"));
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }
}

    private void autoId() {
    try {
        String sql = "SELECT MAX(id_barang) FROM barang";
        ResultSet rs = Koneksi.getKoneksi().createStatement().executeQuery(sql);

        if (rs.next() && rs.getString(1) != null) {
            String id = rs.getString(1); // contoh: BRG005
            int angka = Integer.parseInt(id.substring(3)); // ambil 005 → 5
            angka++;

            txtId.setText(String.format("BRG%03d", angka));
        } else {
            txtId.setText("BRG001");
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
        txtId.setText("BRG001");
    }
}
    private void loadLokasi() {
    try {
        cbLokasi.removeAllItems();
        String sql = "SELECT nama_ruangan FROM ruangan"; // Mengambil data dari tabel ruangan
        ResultSet rs = Koneksi.getKoneksi().createStatement().executeQuery(sql);

        while (rs.next()) {
            cbLokasi.addItem(rs.getString("nama_ruangan"));
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Gagal memuat lokasi: " + e.getMessage());
    }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableBarang = new javax.swing.JTable();
        txtId = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        cbKategori = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbKondisi = new javax.swing.JComboBox<>();
        txtStok = new javax.swing.JTextField();
        cbLokasi = new javax.swing.JComboBox<>();
        btnHome = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FORM DATA BARANG");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 970, -1));

        jLabel2.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        jLabel2.setText("ID Barang");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setText("Nama Barang ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel4.setText("Kategori");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, -1));

        btnSimpan.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        jPanel1.add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 321, -1, 40));

        btnEdit.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel1.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 321, 71, 40));

        btnHapus.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        jPanel1.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 321, -1, 40));

        btnReset.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel1.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 321, -1, 40));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("DATA BARANG");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 970, -1));

        tableBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nama", "Kategori", "Stok", "Kondisi", "Lokasi"
            }
        ));
        tableBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableBarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableBarang);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 450, 467, 124));

        txtId.setBackground(new java.awt.Color(0, 204, 204));
        txtId.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 134, -1));

        txtNama.setBackground(new java.awt.Color(0, 204, 204));
        txtNama.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtNama.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 134, -1));

        cbKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 134, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel6.setText("Kondisi");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel5.setText("Stok");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel7.setText("Lokasi");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 230, -1, -1));

        cbKondisi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbKondisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbKondisiActionPerformed(evt);
            }
        });
        jPanel1.add(cbKondisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 170, 134, -1));

        txtStok.setBackground(new java.awt.Color(0, 204, 204));
        txtStok.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtStok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStokActionPerformed(evt);
            }
        });
        jPanel1.add(txtStok, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, 134, -1));

        cbLokasi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbLokasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 230, 140, -1));

        btnHome.setBackground(new java.awt.Color(51, 153, 255));
        btnHome.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        jPanel1.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 60, -1, 40));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 310, 970, 600));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Animasi Min 18 Jakarta 2.png"))); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1960, 1180));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbKondisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbKondisiActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_cbKondisiActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
     if (txtId.getText().trim().isEmpty()
        || txtNama.getText().trim().isEmpty()
        || txtStok.getText().trim().isEmpty()
        || cbLokasi.getSelectedItem() == null) { // Perubahan validasi lokasi

        JOptionPane.showMessageDialog(this, "Semua data harus diisi!");
        return;
    }

    try {
        java.sql.Connection conn = Koneksi.getKoneksi();
        
        // 1. Cari id_kategori berdasarkan nama_kategori yang dipilih di ComboBox
        String namaKategoriPilihan = cbKategori.getSelectedItem().toString();
        String idKategori = "";
        
        String sqlCariKategori = "SELECT id_kategori FROM kategori WHERE nama_kategori = ?";
        PreparedStatement pstKat = conn.prepareStatement(sqlCariKategori);
        pstKat.setString(1, namaKategoriPilihan);
        ResultSet rsKat = pstKat.executeQuery();
        
        if (rsKat.next()) {
            idKategori = rsKat.getString("id_kategori");
        }
        pstKat.close();
        
        if (idKategori.equals("")) {
            JOptionPane.showMessageDialog(this, "Kategori tidak ditemukan di database!");
            return;
        }

        // 2. Proses Insert
        String sql = "INSERT INTO barang VALUES (?,?,?,?,?,?)";
        PreparedStatement pst = conn.prepareStatement(sql);

        pst.setString(1, txtId.getText());
        pst.setString(2, txtNama.getText());
        pst.setString(3, idKategori); 
        pst.setInt(4, Integer.parseInt(txtStok.getText()));
        pst.setString(5, cbKondisi.getSelectedItem().toString());
        pst.setString(6, cbLokasi.getSelectedItem().toString()); // PERBAIKAN: Menggunakan ComboBox

        pst.executeUpdate();
        pst.close();

        JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
        tampilData();
        btnResetActionPerformed(evt); // Menggunakan reset agar form bersih sempurna dan ID Baru ter-generate

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error Simpan: " + e.getMessage());
    }          // TODO add your handling code here:
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
     try {
        java.sql.Connection conn = Koneksi.getKoneksi();
        
        String namaKategoriPilihan = cbKategori.getSelectedItem().toString();
        String idKategori = "";
        
        String sqlCariKategori = "SELECT id_kategori FROM kategori WHERE nama_kategori = ?";
        PreparedStatement pstKat = conn.prepareStatement(sqlCariKategori);
        pstKat.setString(1, namaKategoriPilihan);
        ResultSet rsKat = pstKat.executeQuery();
        
        if (rsKat.next()) {
            idKategori = rsKat.getString("id_kategori");
        }
        pstKat.close();

        // Proses Update
        String sql = "UPDATE barang SET nama_barang=?, id_kategori=?, stok=?, kondisi=?, lokasi=? WHERE id_barang=?";
        PreparedStatement pst = conn.prepareStatement(sql);

        pst.setString(1, txtNama.getText());
        pst.setString(2, idKategori); 
        pst.setInt(3, Integer.parseInt(txtStok.getText()));
        pst.setString(4, cbKondisi.getSelectedItem().toString());
        pst.setString(5, cbLokasi.getSelectedItem().toString()); // PERBAIKAN: Menggunakan ComboBox
        pst.setString(6, txtId.getText());

        pst.executeUpdate();
        pst.close();

        JOptionPane.showMessageDialog(null, "Data berhasil diupdate");
        tampilData();
        btnResetActionPerformed(evt);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error Edit: " + e.getMessage());
    }                                                                      
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        try {
            String sql = "DELETE FROM barang WHERE id_barang=?";
            PreparedStatement pst = Koneksi.getKoneksi().prepareStatement(sql);

            pst.setString(1, txtId.getText());
            pst.executeUpdate();

            JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
            tampilData();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
    txtNama.setText("");
    txtStok.setText("");
    cbKategori.setSelectedIndex(0);
    cbKondisi.setSelectedIndex(0); 
    if(cbLokasi.getItemCount() > 0) {
        cbLokasi.setSelectedIndex(0); 
    }
    autoId();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnResetActionPerformed

    private void tableBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableBarangMouseClicked
        int baris = tableBarang.getSelectedRow();

        txtId.setText(tableBarang.getValueAt(baris, 0).toString());
        txtNama.setText(tableBarang.getValueAt(baris, 1).toString());
        cbKategori.setSelectedItem(tableBarang.getValueAt(baris, 2).toString());
        txtStok.setText(tableBarang.getValueAt(baris, 3).toString());
        cbKondisi.setSelectedItem(tableBarang.getValueAt(baris, 4).toString());
        cbLokasi.setSelectedItem(tableBarang.getValueAt(baris, 5).toString());       // TODO add your handling code here:
    }//GEN-LAST:event_tableBarangMouseClicked

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
dashboard db = new dashboard();

    db.setVisible(true);

    this.dispose();       // TODO add your handling code here:
    }//GEN-LAST:event_btnHomeActionPerformed

    private void txtStokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStokActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormBarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cbKategori;
    private javax.swing.JComboBox<String> cbKondisi;
    private javax.swing.JComboBox<String> cbLokasi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableBarang;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtStok;
    // End of variables declaration//GEN-END:variables

}
