/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan.master;
import Koneksi.Koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import tampilan.dashboard.dashboard;

/**
 *
 * @author andre_f1brqrv
 */
public class FormSupplier extends javax.swing.JFrame {
    Connection conn = Koneksi.getKoneksi();
    DefaultTableModel model;

    /**
     * Creates new form menusupplier
     */
    public FormSupplier() {
        initComponents();
        tampilData();
        resetForm();
    }

    
    private void tampilData() {

    model = new DefaultTableModel();

    model.addColumn("ID Supplier");
    model.addColumn("Nama Supplier");
    model.addColumn("Alamat");
    model.addColumn("No Telpon");

    tblSupplier.setModel(model);

    try {

        String sql = "SELECT * FROM supplier";
        Statement st = conn.createStatement();
        ResultSet rs = st.executeQuery(sql);

        while(rs.next()){

            model.addRow(new Object[]{
    rs.getString("id_supplier"),
    rs.getString("nama_supplier"),
    rs.getString("alamat"),
    rs.getString("no_telp") });
           
        }
    } catch (Exception e){
        JOptionPane.showMessageDialog(null, e.getMessage());
    }
}
    
    private void resetForm(){

    txtIdSupplier.setText("");
    txtNamaSupplier.setText("");
    txtAlamat.setText("");
    txtNoTelpon.setText("");

    txtIdSupplier.requestFocus();

}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtIdSupplier = new javax.swing.JTextField();
        txtNamaSupplier = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtAlamat = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNoTelpon = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btnhome = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSupplier = new javax.swing.JTable();
        txtcari1 = new javax.swing.JTextField();
        txtCari = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel10.setText("ID Supplier");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        txtIdSupplier.setBackground(new java.awt.Color(0, 204, 204));
        txtIdSupplier.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        txtIdSupplier.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel2.add(txtIdSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 251, -1));

        txtNamaSupplier.setBackground(new java.awt.Color(0, 204, 204));
        txtNamaSupplier.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        txtNamaSupplier.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel2.add(txtNamaSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 251, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel6.setText("Nama Supplier");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        txtAlamat.setBackground(new java.awt.Color(0, 204, 204));
        txtAlamat.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        txtAlamat.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlamatActionPerformed(evt);
            }
        });
        jPanel2.add(txtAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 251, 30));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel7.setText("Alamat");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel8.setText("No Telepon");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 104, 27));

        txtNoTelpon.setBackground(new java.awt.Color(0, 204, 204));
        txtNoTelpon.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        txtNoTelpon.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtNoTelpon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoTelponActionPerformed(evt);
            }
        });
        jPanel2.add(txtNoTelpon, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 251, 27));

        btnSimpan.setBackground(new java.awt.Color(0, 255, 0));
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        jPanel2.add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("FORM DATA SUPPLIER");
        jLabel9.setToolTipText("");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 20, 720, 47));

        btnhome.setBackground(new java.awt.Color(204, 255, 255));
        btnhome.setText("HOME");
        btnhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhomeActionPerformed(evt);
            }
        });
        jPanel2.add(btnhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, -1, -1));

        btnEdit.setBackground(new java.awt.Color(255, 153, 51));
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel2.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, -1, -1));

        btnHapus.setBackground(new java.awt.Color(255, 0, 51));
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        jPanel2.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 369, -1, 30));

        btnReset.setBackground(new java.awt.Color(204, 204, 204));
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel2.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, -1, -1));

        tblSupplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblSupplier.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblSupplierKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(tblSupplier);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 510, 504, 110));

        txtcari1.setBackground(new java.awt.Color(0, 204, 204));
        txtcari1.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtcari1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel2.add(txtcari1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, 174, 34));

        txtCari.setText("Cari");
        txtCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCariActionPerformed(evt);
            }
        });
        jPanel2.add(txtCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 450, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 260, 720, 730));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Animasi Min 18 Jakarta 4.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 2050, 1430));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 1430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
try{

        String sql =
    "INSERT INTO supplier (id_supplier, nama_supplier, alamat, no_telp) VALUES (?,?,?,?)";

PreparedStatement ps = conn.prepareStatement(sql);
ps.setString(1, txtIdSupplier.getText());
ps.setString(2, txtNamaSupplier.getText());
ps.setString(3, txtAlamat.getText());
ps.setString(4, txtNoTelpon.getText());

ps.executeUpdate();

        JOptionPane.showMessageDialog(null, "Data berhasil disimpan");

        tampilData();
        resetForm();

    }catch(Exception e){

        JOptionPane.showMessageDialog(null, e.getMessage());

    }        // TODO add your handling code here:
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
 try{

        String sql = "UPDATE supplier SET "
        + "nama_supplier=?, "
        + "alamat=?, "
        + "no_telp=? "
        + "WHERE id_supplier=?";

        PreparedStatement ps = conn.prepareStatement(sql);

ps.setString(1, txtNamaSupplier.getText());
ps.setString(2, txtAlamat.getText());
ps.setString(3, txtNoTelpon.getText());
ps.setString(4, txtIdSupplier.getText());

ps.executeUpdate();

JOptionPane.showMessageDialog(null, "Data berhasil diubah");
tampilData();
resetForm();

    }catch(Exception e){

        JOptionPane.showMessageDialog(null, e.getMessage());

    }       // TODO add your handling code here:
    }//GEN-LAST:event_btnEditActionPerformed

    private void txtAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlamatActionPerformed

    private void txtCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariActionPerformed
 model.setRowCount(0);

    try{

        String sql =
            "SELECT * FROM supplier " +
            "WHERE id_supplier LIKE '%"+txtCari.getText()+"%' " +
            "OR nama_supplier LIKE '%"+txtCari.getText()+"%'";

        Statement st = conn.createStatement();
        ResultSet rs = st.executeQuery(sql);

        while(rs.next()){

            model.addRow(new Object[]{

                rs.getString("id_supplier"),
                rs.getString("nama_supplier"),
                rs.getString("alamat"),
                rs.getString("no_telp")

            });

        }

    }catch(Exception e){

        JOptionPane.showMessageDialog(null,e.getMessage());

    }
            // TODO add your handling code here:
    }//GEN-LAST:event_txtCariActionPerformed

    private void btnhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhomeActionPerformed
    dashboard db = new dashboard();

    db.setVisible(true);

    this.dispose();     // TODO add your handling code here:
    }//GEN-LAST:event_btnhomeActionPerformed

    private void txtNoTelponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoTelponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoTelponActionPerformed

    private void tblSupplierKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblSupplierKeyPressed
 int baris = tblSupplier.getSelectedRow();

    txtIdSupplier.setText(model.getValueAt(baris,0).toString());
    txtNamaSupplier.setText(model.getValueAt(baris,1).toString());
    txtAlamat.setText(model.getValueAt(baris,2).toString());
    txtNoTelpon.setText(model.getValueAt(baris,3).toString());        // TODO add your handling code here:
    }//GEN-LAST:event_tblSupplierKeyPressed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
try{

        String sql = "DELETE FROM supplier WHERE id_supplier=?";

        PreparedStatement ps = conn.prepareStatement(sql);

        ps.setString(1, txtIdSupplier.getText());

        ps.executeUpdate();

        JOptionPane.showMessageDialog(null, "Data berhasil dihapus");

        tampilData();
        resetForm();

    }catch(Exception e){

        JOptionPane.showMessageDialog(null, e.getMessage());

    }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
resetForm();        // TODO add your handling code here:
    }//GEN-LAST:event_btnResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormSupplier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnhome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblSupplier;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JButton txtCari;
    private javax.swing.JTextField txtIdSupplier;
    private javax.swing.JTextField txtNamaSupplier;
    private javax.swing.JTextField txtNoTelpon;
    private javax.swing.JTextField txtcari1;
    // End of variables declaration//GEN-END:variables
}
