/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan.master;
import Koneksi.Koneksi;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import tampilan.dashboard.dashboard;

/**
 *
 * @author raisa
 */
public class FormRuangan extends javax.swing.JFrame {
    private Connection conn = Koneksi.getKoneksi(); 
    private DefaultTableModel tabmode;
    /**
     * Creates new form FormRuangan
     */
    public FormRuangan() {
         initComponents();
        aktif();      
        datatable();
        autoId();    
    }
     protected void aktif(){
        txtIdRuangan.requestFocus();
    }

    // Membersihkan isi textfield
    protected void kosong(){
        txtIdRuangan.setText("");
        txtNamaRuangan.setText("");
    }

    // Menampilkan data dari database ke JTable (tblkategori)
    protected void datatable(){
        // Header tabel sesuai ERD Kategori
        Object[] Baris = {"ID Ruangan", "Nama Ruangan", "Lokasi"};
        tabmode = new DefaultTableModel(null, Baris);
        
        try {
            // Query mengambil data dari tabel kategori
            String sql = "SELECT * FROM ruangan order by id_ruangan asc";
            Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            
            while (hasil.next()) {
                tabmode.addRow(new Object[]{
                    hasil.getString("id_ruangan"),
                    hasil.getString("nama_ruangan"),
                    hasil.getString("lokasi")
                });
            }
            // Mengatur model ke variabel tabel kamu
            tblRuangan.setModel(tabmode);
        } catch (SQLException e){
            JOptionPane.showMessageDialog(null, "Data gagal dipanggil: " + e);
        }
    }

    private void autoId() {
    try {
        String sql = "SELECT MAX(id_ruangan) FROM ruangan";
        ResultSet rs = Koneksi.getKoneksi().createStatement().executeQuery(sql);

        if (rs.next() && rs.getString(1) != null) {
            String id = rs.getString(1); // contoh: BRG005
            int angka = Integer.parseInt(id.substring(3)); // ambil 005 → 5
            angka++;

            txtIdRuangan.setText(String.format("RNG%03d", angka));
        } else {
            txtIdRuangan.setText("RNG001");
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
        txtIdRuangan.setText("RNG001");
    }
}
    // Fungsi untuk menampilkan data dari database ke JTable dan fitur Pencarian
private void tampilData(String cari) {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID Ruangan");
    model.addColumn("Nama Ruangan");
    model.addColumn("Lokasi");
    
    try {
        java.sql.Connection conn = Koneksi.getKoneksi();
        String sql;
        
        // Jika kolom cari kosong tampilkan semua, jika terisi lakukan filter
        if (cari.equals("")) {
            sql = "SELECT * FROM ruangan";
        } else {
            sql = "SELECT * FROM ruangan WHERE id_ruangan LIKE '%" + cari + "%' OR nama_ruangan LIKE '%" + cari + "%' OR lokasi LIKE '%" + cari + "%'";
        }
        
        java.sql.Statement st = conn.createStatement();
        java.sql.ResultSet rs = st.executeQuery(sql);
        
        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString("id_ruangan"),
                rs.getString("nama_ruangan"),
                rs.getString("lokasi")
            });
        }
        tblRuangan.setModel(model);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal memuat data: " + e.getMessage());
    }
}

// Fungsi untuk mengosongkan form inputan
private void resetForm() {
    txtIdRuangan.setText("");
    txtNamaRuangan.setText("");
    txtLokasi.setText("");
    txtCari.setText("");
    txtIdRuangan.setEditable(true); // Membuka kembali kunci ID Ruangan
    txtIdRuangan.requestFocus();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtIdRuangan = new javax.swing.JTextField();
        txtNamaRuangan = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtLokasi = new javax.swing.JTextField();
        btnHome = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRuangan = new javax.swing.JTable();
        btnCari = new javax.swing.JButton();
        txtCari = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 35)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FORM DATA RUANGAN");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 740, 47));

        jLabel2.setText("ID Ruangan :");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 119, 30));

        txtIdRuangan.setBackground(new java.awt.Color(0, 204, 204));
        txtIdRuangan.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtIdRuangan.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel2.add(txtIdRuangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 200, -1));

        txtNamaRuangan.setBackground(new java.awt.Color(0, 204, 204));
        txtNamaRuangan.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtNamaRuangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaRuanganActionPerformed(evt);
            }
        });
        jPanel2.add(txtNamaRuangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 200, -1));

        jLabel3.setText("Nama Ruangan :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, 34));

        jLabel4.setText("Lokasi :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 119, 34));

        txtLokasi.setBackground(new java.awt.Color(0, 204, 204));
        txtLokasi.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtLokasi.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel2.add(txtLokasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 200, 34));

        btnHome.setBackground(new java.awt.Color(204, 255, 255));
        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        jPanel2.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 90, 93, 38));

        tblRuangan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblRuangan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRuanganMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblRuangan);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 570, -1, 142));

        btnCari.setText("CARI");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });
        jPanel2.add(btnCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 520, -1, -1));

        txtCari.setBackground(new java.awt.Color(0, 204, 204));
        txtCari.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel2.add(txtCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 530, 158, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("DATA RUANGAN");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 730, -1));

        btnSimpan.setBackground(new java.awt.Color(0, 255, 0));
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        jPanel2.add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 99, 41));

        btnEdit.setBackground(new java.awt.Color(255, 153, 51));
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel2.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 78, 41));

        btnHapus.setBackground(new java.awt.Color(255, 0, 0));
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        jPanel2.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, 92, 41));

        btnReset.setBackground(new java.awt.Color(204, 204, 204));
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel2.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, 92, 41));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 200, 760, 770));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Animasi Min 18 Jakarta 3.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1130));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1140));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamaRuanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaRuanganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaRuanganActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
                                        
    resetForm();
    tampilData("");  // TODO add your handling code here:
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
    dashboard db = new dashboard();

    db.setVisible(true);

    this.dispose();    // TODO add your handling code here:
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
    if (txtIdRuangan.getText().equals("") || txtNamaRuangan.getText().equals("") || txtLokasi.getText().equals("")) {
        JOptionPane.showMessageDialog(this, "Semua data harus diisi!");
    } else {
        try {
            String sql = "INSERT INTO ruangan (id_ruangan, nama_ruangan, lokasi) VALUES (?, ?, ?)";
            java.sql.Connection conn = Koneksi.getKoneksi();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            
            pst.setString(1, txtIdRuangan.getText());
            pst.setString(2, txtNamaRuangan.getText());
            pst.setString(3, txtLokasi.getText());
            
            pst.execute();
            JOptionPane.showMessageDialog(null, "Penyimpanan Data Berhasil");
            tampilData("");
            resetForm();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }    // TODO add your handling code here:
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
    if (txtIdRuangan.getText().equals("")) {
        JOptionPane.showMessageDialog(this, "Pilih data di tabel yang ingin diubah terlebih dahulu!");
    } else {
        try {
            String sql = "UPDATE ruangan SET nama_ruangan = ?, lokasi = ? WHERE id_ruangan = ?";
            java.sql.Connection conn = Koneksi.getKoneksi();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            
            pst.setString(1, txtNamaRuangan.getText());
            pst.setString(2, txtLokasi.getText());
            pst.setString(3, txtIdRuangan.getText());
            
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data Berhasil Diperbarui");
            tampilData("");
            resetForm();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal mengubah data: " + e.getMessage());
        }
    }
    // TODO add your handling code here:
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
    if (txtIdRuangan.getText().equals("")) {
        JOptionPane.showMessageDialog(this, "Pilih data di tabel yang ingin dihapus terlebih dahulu!");
    } else {
        int konfirmasi = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin menghapus data ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (konfirmasi == JOptionPane.YES_OPTION) {
            try {
                String sql = "DELETE FROM ruangan WHERE id_ruangan = ?";
                java.sql.Connection conn = Koneksi.getKoneksi();
                java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                pst.setString(1, txtIdRuangan.getText());
                
                pst.execute();
                JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
                tampilData("");
                resetForm();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Gagal menghapus data: " + e.getMessage());
            }
        }
    }
    // TODO add your handling code here:
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
                                       
    tampilData(txtCari.getText());
 // TODO add your handling code here:
    }//GEN-LAST:event_btnCariActionPerformed

    private void tblRuanganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRuanganMouseClicked
    int baris = tblRuangan.rowAtPoint(evt.getPoint());
    
    // Ambil data dari baris tabel yang diklik
    String id = tblRuangan.getValueAt(baris, 0).toString();
    String nama = tblRuangan.getValueAt(baris, 1).toString();
    String lokasi = tblRuangan.getValueAt(baris, 2).toString();
    
    // Set nilai ke komponen Input Form
    txtIdRuangan.setText(id);
    txtNamaRuangan.setText(nama);
    txtLokasi.setText(lokasi);
    
    // Mengunci inputan ID Ruangan agar Primary Key tidak diubah sembarangan saat proses Edit
    txtIdRuangan.setEditable(false);     // TODO add your handling code here:
    }//GEN-LAST:event_tblRuanganMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormRuangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormRuangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormRuangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormRuangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormRuangan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRuangan;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtIdRuangan;
    private javax.swing.JTextField txtLokasi;
    private javax.swing.JTextField txtNamaRuangan;
    // End of variables declaration//GEN-END:variables

}
