/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan.report;


import Koneksi.Koneksi;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author andre_f1brqrv
 */
public class FormReport extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormReport
     */
    public FormReport() {
        initComponents();
        
    
    setIconifiable(true);
    setMaximizable(true);
    setResizable(true);

    cbReport.removeAllItems();
    cbReport.addItem("Data Barang");
    cbReport.addItem("Barang Masuk");
    cbReport.addItem("Kerusakan");
    cbReport.addItem("Mutasi");

    tableReport.setRowHeight(25);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbReport = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTanggalAwal = new javax.swing.JTextField();
        txtTanggalAkhir = new javax.swing.JTextField();
        btnTampil = new javax.swing.JButton();
        btnCetak = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableReport = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("FORM  REPORT INVENTORI");

        jLabel2.setText("Pilih Report :");

        cbReport.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Data Barang", "Barang Masuk", "Kerusakan", "Mutasi" }));

        jLabel3.setText("Tanggal Awal  :");

        jLabel4.setText("Tanggal Akhir :");

        btnTampil.setText("TAMPILKAN ");
        btnTampil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTampilActionPerformed(evt);
            }
        });

        btnCetak.setText("CETAK PDF");

        btnReset.setText("RESET ");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        jLabel5.setText("Hasil Report");

        tableReport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableReport);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnTampil)
                                .addGap(18, 18, 18)
                                .addComponent(btnCetak)
                                .addGap(28, 28, 28)
                                .addComponent(btnReset))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtTanggalAwal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                        .addComponent(txtTanggalAkhir, javax.swing.GroupLayout.Alignment.LEADING))))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTanggalAwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTanggalAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTampil)
                    .addComponent(btnCetak)
                    .addComponent(btnReset))
                .addGap(32, 32, 32)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(325, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        
    private void btnTampilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTampilActionPerformed

        String pilih =
    cbReport.getSelectedItem().toString();

    DefaultTableModel model =
    new DefaultTableModel();

    try {

        Connection conn =
        Koneksi.getKoneksi();

        Statement st =
        conn.createStatement();

        ResultSet rs = null;

        // REPORT BARANG
        if(pilih.equals("Data Barang")){

            model.addColumn("ID Barang");
            model.addColumn("Nama Barang");
            model.addColumn("Kategori");
            model.addColumn("Stok");
            model.addColumn("Kondisi");

            String sql =
            "SELECT * FROM barang";

            rs = st.executeQuery(sql);

            while(rs.next()){

                model.addRow(new Object[]{

                    rs.getString("id_barang"),
                    rs.getString("nama_barang"),
                    rs.getString("kategori"),
                    rs.getString("stok"),
                    rs.getString("kondisi")
                });
            }
        }

        // REPORT BARANG MASUK
        else if(pilih.equals("Barang Masuk")){

            model.addColumn("ID");
            model.addColumn("Tanggal");
            model.addColumn("Barang");
            model.addColumn("Supplier");
            model.addColumn("Jumlah");

            String sql =
            "SELECT bm.id_transaksi, bm.tanggal, " +
            "b.nama_barang, s.nama_supplier, bm.jumlah " +
            "FROM barang_masuk bm " +
            "JOIN barang b ON bm.id_barang=b.id_barang " +
            "JOIN supplier s ON bm.id_supplier=s.id_supplier";

            rs = st.executeQuery(sql);

            while(rs.next()){

                model.addRow(new Object[]{

                    rs.getString("id_transaksi"),
                    rs.getString("tanggal"),
                    rs.getString("nama_barang"),
                    rs.getString("nama_supplier"),
                    rs.getString("jumlah")
                });
            }
        }

        // REPORT KERUSAKAN
        else if(pilih.equals("Kerusakan")){

            model.addColumn("ID");
            model.addColumn("Tanggal");
            model.addColumn("Barang");
            model.addColumn("Jumlah");
            model.addColumn("Keterangan");

            String sql =
            "SELECT k.id_kerusakan, k.tanggal, " +
            "b.nama_barang, k.jumlah_rusak, " +
            "k.keterangan " +
            "FROM kerusakan k " +
            "JOIN barang b ON k.id_barang=b.id_barang";

            rs = st.executeQuery(sql);

            while(rs.next()){

                model.addRow(new Object[]{

                    rs.getString("id_kerusakan"),
                    rs.getString("tanggal"),
                    rs.getString("nama_barang"),
                    rs.getString("jumlah_rusak"),
                    rs.getString("keterangan")
                });
            }
        }

        // REPORT MUTASI
        else if(pilih.equals("Mutasi")){

            model.addColumn("ID");
            model.addColumn("Tanggal");
            model.addColumn("Barang");
            model.addColumn("Asal");
            model.addColumn("Tujuan");
            model.addColumn("Jumlah");

            String sql =
            "SELECT m.id_mutasi, m.tanggal, " +
            "b.nama_barang, " +
            "r1.nama_ruangan AS asal, " +
            "r2.nama_ruangan AS tujuan, " +
            "m.jumlah " +
            "FROM mutasi m " +
            "JOIN barang b ON m.id_barang=b.id_barang " +
            "JOIN ruangan r1 ON m.ruangan_asal=r1.id_ruangan " +
            "JOIN ruangan r2 ON m.ruangan_tujuan=r2.id_ruangan";

            rs = st.executeQuery(sql);

            while(rs.next()){

                model.addRow(new Object[]{

                    rs.getString("id_mutasi"),
                    rs.getString("tanggal"),
                    rs.getString("nama_barang"),
                    rs.getString("asal"),
                    rs.getString("tujuan"),
                    rs.getString("jumlah")
                });
            }
        }

        tableReport.setModel(model);

    } catch(Exception e){

        JOptionPane.showMessageDialog(null, e);
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTampilActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
 txtTanggalAwal.setText("");
    txtTanggalAkhir.setText("");

    cbReport.setSelectedIndex(0);        // TODO add your handling code here:
    }//GEN-LAST:event_btnResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTampil;
    private javax.swing.JComboBox<String> cbReport;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableReport;
    private javax.swing.JTextField txtTanggalAkhir;
    private javax.swing.JTextField txtTanggalAwal;
    // End of variables declaration//GEN-END:variables
}
